/* Modelagem Básica - 
ENDITADE = TABELA
CAMPOS = ATRIBUTOS
 */
CLIENTE

CONJUGE - SIM NAO
NOME_CONJUGE - CARACTERE(50)
NOME - CARACTERE(50)
CPF - 
NACIONALIDADE
PROFISSAO
NASCIMENTO
NASCIMENTO
DATA_CASAMENTO
ESTADO_CIVIL
DOC_IDENTIDADE
ORGAO_EXPEDIDOR
DATA_EXPEDICAO
ASS_CARTORIO
CEP
TIPO
LOGRADOURO
NUMERO
COMPLEMENTO
BAIRRO
CIDADE
UF
EMAIL_1
EMAIL_2
CELULAR
RESIDENCIA
COMERCIAL
RECADO


/* MODELAGEM FÍSICA */

/* Criando o bando de dados */
CREATE DATABASE projeto;

/* Conectando ao banco de dados */
USE PROJETO;

/* Criando a tabela de clientes */
CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/* Verificando as tabelas do banco */
SHOW TABLES;

/* Descobrindo como é a estrutura de uma tabela */
DESC CLIENTE;

/* FORMA 1 - OMITINDO AS COLUNAS */
INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MARIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 2 - COLOCANDO AS COLUNAS */
INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('CLARA', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '883665843', 04121235681);

/* FORMA 3 - INSERT COMPACTO - SOMENTE MYSQL */
INSERT INTO CLIENTE VALUES('ANA', 'F', 'ANA@GLOBO.COM', 85548962, '548556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'), ('CARLA', 'F', 'CARLA@TERATI.COM.BR', 7745828, '66587458', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/* O COMANDO SELECT */
SELECT NOW();

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */
SELECT * FROM CLIENTE;

/* FILTRANDO */
SELECT NOME, SEXO FROM CLIENTE WHERE SEXO = 'M';

SELECT NOME AS CLIENTE, ENDERECO AS RUA FROM CLIENTE WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%CENTRO%';

/* EXERCÍCIO LIVRARIA */
CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
    NOME_LIVRO VARCHAR(30),
    NOME_AUTOR VARCHAR(30),
    SEXO_AUTOR CHAR(1),
    NUM_PAGINAS INT,
    NOME_EDITORA VARCHAR(30),
    VALOR_LIVRO FLOAT(5,2),
    UF_EDITORA CHAR(2),
    ANO_PUBLICACAO INT
);

USE LIVRARIA;

DESC LIVROS;

INSERT INTO LIVROS VALUES('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009), ('SQL PARA LEIGOS', 'JOAO NUNES', 'M', 450, 'ADDISON', 98, 'SP', 2018), ('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F',210, 'ATLAS', 45, 'RJ', 2008), ('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018), ('HABITOS SAUDAVEIS', 'EDUARDO SANTOS', 'M', 630, 'BETA', '150.98', 'RJ', 2019), ('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60, 'MG', 2016), ('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', 310, 'INSIGNIA', 78.98, 'ES', 2011), ('COPAS INESQUECIVEIS', 'MARCO ALCANTARA', 'M', 200, 'LARSON', 130.98, 'RS', 2018), ('O PODER DA MENTE', 'CLARA MAFRA', 'F', 120, 'CONTINENTAL', 56.58, 'SP', 2017);

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUM_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO) VALUES('PRA SEMPRE AMIGAS', 'LEDA SILVA', 'F', 510, 'INSIGNIA', 100, 'ES', 2015);

SELECT * FROM LIVROS;

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

SELECT NOME_LIVRO, UF_EDITORA FROM LIVROS WHERE SEXO_AUTOR = 'M';

SELECT NOME_LIVRO, NUM_PAGINAS FROM LIVROS WHERE SEXO_AUTOR = 'F';

SELECT VALOR_LIVRO FROM LIVROS WHERE UF_EDITORA = 'SP';

SELECT * FROM LIVROS WHERE SEXO_AUTOR = 'M' AND (UF_EDITORA = 'SP' OR UF_EDITORA = 'RJ');

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LÓGIGOS */

SELECT COUNT(*) AS 'QUANTIDADE DE REGISTROS DA TABELA CLIENTE' FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

/* PERFORMANCE EM OPERADORES LOGICOS */

/* 1 MILHAO DE REGISTROS

PARA CONTAR
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDICAO
SEXO = F
CIDADE = RIO DE JANEIRO

SITUACAO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'RIO DE JANEIRO';

SITUACAO - TRATANDO COM E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE CIDADE = 'RIO DE JANEIRO'
AND SEXO = 'F';
*/

/* EXERCÍCIO */
-- 1 - TRAGA OS FUNCIONÁRIOS QUE TRABALHAM NO DEPARTAMENTO DE FILEMS OU NO DEPARTAMENTO DE ROUPAS
SELECT * FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ROUPAS' OR DEPARTAMENTO = 'FILMES';

-- 2 - O GESTRO DE MARKENTIN PEDIU A LISTA DAS FUNCIONÁRIAS QUE TRABALHAM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO LAR. ELE NECESSITA ENVIAR UM EMAIL PARA AS COLABORADORS DESESS DOIS SETORES.
SELECT COUNT(*), SEXO FROM FUNCIONARIOS GROUP BY SEXO;
SELECT COUNT(*), DEPARTAMENTO FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;
SELECT * FROM FUNCIONARIOS WHERE (DEPARTAMENTO = 'LAR' AND SEXO = 'FEMININO') OR (DEPARTAMENTO = 'FILMES' AND SEXO = 'FEMININO');

-- 3 - TRAGA OS FUNCIONÁRIOS DO SEXO MASCULINO OU OS FUNCIONARIOS QUE TRABALHEAM NO SERTOR JARDIM
SELECT COUNT(*), SEXO FROM FUNCIONARIOS GROUP BY SEXO;
SELECT COUNT(*), DEPARTAMENTO FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;
SELECT * FROM FUNCIONARIOS WHERE SEXO = 'MASCULINO' OR DEPARTAMENTO = 'JARDIM';


create database exercicio;

use exercicio;

create table funcionarios
  (
      idFuncionario integer,
      nome varchar(100),
      email varchar(200),
      sexo varchar(10),
      departamento varchar(100),
      admissao varchar(10),
      salario integer,
      cargo varchar(100),
      idRegiao int
  );

/* FILTRANDO VALORES NULOS */
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NOT NULL;

/* ISN OU IN NOT NULL */

/* UTILIZANDO O UPDAE PARA ATUALIZAR VALORES */
SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'LILIAN@HOTMAIL.COM';

/* WHERE - VAI SER O SEU MELHOR AMIGO DA VIDA PARA VIDA INTEIRA */
UPDATE CLIENTE SET EMAIL = 'JOAO@IG.COM.BR' WHERE NOME = 'JOAO';
UPDATE CLIENTE SET EMAIL = 'JORGE@IG.COM.BR' WHERE NOME = 'JORGE';
UPDATE CLIENTE SET EMAIL = 'CELIA@GMAIL.COM' WHERE NOME = 'CELIA';
UPDATE CLIENTE SET EMAIL = 'ANA@GLOBO.COM' WHERE NOME = 'ANA';
UPDATE CLIENTE SET EMAIL = 'CARLA@TERATI.COM.BR' WHERE NOME = 'CARLA';

/* DELETANDO REGISTROS COM A CLÁUSULA DELETE */
SELECT COUNT(*) FROM CLIENTE; -- 7 REGISTROS

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'CLARA'; -- 1 REGISTRO

DELETE FROM CLIENTE WHERE NOME = 'CLARA';

SELECT COUNT(*) FROM CLIENTE; -- 6 REGISTROS

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE VALUES('CARAL', 'F', 'C.LOPES@UOL.COM', 45638854, '4557-0048', 'RUA COPPER LEAF - WILIAMASBURG - KITCHENER');

SELECT * FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'CARLA@TERATI.COM.BR';

DELETE FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'CARLA@TERATI.COM.BR';

/* MODELAGEM DE BANCO DE DADOS PARA SISTEMAS */

/* PRIMEIRA FORMA NORMAL 
1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA;
[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABLELA. QUANDO O CAMPO FOR DIVISÍVEL;

3 - TODA TABELA NECESSITA DE PLEO MENOS UM CAMPO QUE IDENTIFICQUE TODO O REGISRO COMO SENDO ÚNICO.
ISSO É O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY.
*/
CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL, 
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

/* ENDEREÇO - OBRIGATÓRIO CADASTRO DE SOMENTE UM.

TELEFONE - NÃO OBRIGATÓRIO CADASTRO DE MAIS DE UM (OPCIONAL)
 */

 /* CHAVE ESTRANGEIRA: Á A CHAVE PRIMARIA DE UMA TABVELA QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERÊNCIA ENTRE REGISTROS */
/* EM RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */
/* EM RALACIOMANENTOS 1 X N A CHAVE ESTRANGEIRA FICA SEMPRE NA CARDINALIDADE N */

/* SELEÇÃO, POJEÇÃO E JUNÇÃO */

/* PORJEÇÃO - É TUDO O QUE VOCÊ QUER VER NA TELA */
SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW() FROM CLIENTE;

/* SELECAO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
A CLAUSULA DE SELECAO É O WHERE */
SELECT NOME, SEXO, EMAIL FROM CLIENTE WHERE SEXO = 'F';

SELECT NUMERO FROM TELEFONE WHERE TIPO = 'CEL';

SELECT NUMERO FROM TELEFONE WHERE ID_CLIENTE = 5;

/* JUNÇÃO - JOIN */
SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE FROM ENDERECO;

+--------+----------------+-----------+
| NOME   | EMAIL          | IDCLIENTE |
+--------+----------------+-----------+
| JOAO   | JOAOA@IG.COM   |         1 |
| CARLOS | CARLOSA@IG.COM |         2 |
| ANA    | ANA@IG.COM     |         3 |
| CLARA  | NULL           |         4 |
| JORGE  | JORGE@IG.COM   |         5 |
| CELIA  | JCELIA@IG.COM  |         6 |
+--------+----------------+-----------+

+------------+----------+----------------+
| ID_CLIENTE | BAIRRO   | CIDADE         |
+------------+----------+----------------+
|          4 | CENTRO   | B. HORIZONTE   |
|          1 | CENTRO   | RIO DE JANEIRO |
|          3 | JARDINS  | SAO PAULO      |
|          2 | ESTACIO  | RIO DE JANEIRO |
|          6 | FLAMENGO | RIO DE JANEIRO |
|          5 | CENTRO   | VITORIA        |
+------------+----------+----------------+

/* NOME, SEXO, BAIRRO, CIDADE */

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE 
    INNER JOIN ENDERECO 
    ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE 
    INNER JOIN ENDERECO 
    ON IDCLIENTE = ID_CLIENTE 
WHERE SEXO = 'F';

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;